[project]
name = "spark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyspark>=3.5.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
